### ISSUE TITLE
Docker image and Kubernetes example

### ISSUE THREAD

**Issue by gg7** [gjcarneiro/yacron#3]
Could you please

1. Create a Docker image on dockerhub
2. Add an example of using said docker image with Kubernetes

Thanks!

**Comment by gjcarneiro** [comment]
I don't think creating a yacron image in dockerhub is useful.  Normally you want yacron to run some of your code.  Creating a docker image with only yacron will only be able to run basic shell commands and nothing more.  Only adding yacron to an existing (possibly private) docker image makes sense to me, so publishing to docker hub is a lot of work and no practical utility. 

I added an example and instructions to build.  Should be fairly obvious how to adapt the build instructions to work with any docker image.

**Comment by ToshY** [comment]
It has been 5 years since this issue was closed, but nowadays it has become pretty straightforward to publish to Docker Hub with [Github actions](https://docs.github.com/en/actions/publishing-packages/publishing-docker-images), so it's no longer "a lot of work".

My use case (or "practicual utility") is quite simple: I just want to test it.
